apiVersion: apps/v1
kind: Deployment
metadata:
  name: contenedores-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contenedores
  template:
    metadata:
      labels:
        app: contenedores
    spec:
      containers:
        - name: contenedores-api
          image: contenedores-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: contenedores-service
spec:
  type: NodePort
  selector:
    app: contenedores
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

